#' Retrieve information on the distance of KNMI weatherstations
#'
#' @param sf shape (centroid is used)
#' @examples
#' knmi <- dist_knmi(sf)

#' @export

dist_knmi <- function(sf){
  #gather locations of KNMI weather stations (originally from TU delft link)----
  locations <- structure(list(StationID = c("209", "215", "225", "235", "240",
                                          "242", "248", "249", "251", "257", "258", "260", "267", "269",
                                          "270", "273", "275", "277", "278", "279", "280", "283", "285",
                                          "286", "290", "308", "310", "312", "313", "315", "316", "319",
                                          "324", "330", "331", "340", "343", "344", "348", "350", "356",
                                          "370", "375", "377", "380", "391"), Naam = c("Ijmond", "Voorschoten",
                                                                                       "Ijmuiden", "De", "Schiphol", "Vlieland", "Wijdenes", "Berkhout",
                                                                                       "Hoorn", "Wijk", "Houtribdijk", "De", "Stavoren", "Lelystad",
                                                                                       "Leeuwarden", "Marknesse", "Deelen", "Lauwersoog", "Heino", "Hoogeveen",
                                                                                       "Eelde", "Hupsel", "Huibertgat", "Nieuw", "Twenthe", "Cadzand",
                                                                                       "Vlissingen", "Oosterschelde", "Vlakte", "Hansweert", "Schaar",
                                                                                       "Westdorpe", "Stavenisse", "Hoek", "Tholen", "Woensdrecht", "R'dam-Geulhaven",
                                                                                       "Rotterdam", "Cabauw", "Gilze-Rijen", "Herwijnen", "Eindhoven",
                                                                                       "Volkel", "Ell", "Maastricht", "Arcen"), geometry = structure(list(
                                                                                         structure(c(95931.093433345, 497826.967197251, 0), class = c("XYZ",
                                                                                                                                                      "POINT", "sfg")), structure(c(89954.2481819271, 461848.936587641,
                                                                                                                                                                                    0), class = c("XYZ", "POINT", "sfg")), structure(c(98442.8814054022,
                                                                                                                                                                                                                                       497574.90524565, 0), class = c("XYZ", "POINT", "sfg")), structure(c(114235.451470764,
                                                                                                                                                                                                                                                                                                           549163.125211842, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(114280.345961269, 481284.207138301, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(123874.837501061, 583924.976961403,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(140566.29430511,
                                                                                                                                                                                                                                        516298.260815722, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(127371.415126819, 517467.64850425, 0), class = c("XYZ",
                                                                                                                                                      "POINT", "sfg")), structure(c(152258.446163919, 600630.434960004,
                                                                                                                                                                                    0), class = c("XYZ", "POINT", "sfg")), structure(c(101756.715050525,
                                                                                                                                                                                                                                       502322.80497157, 0), class = c("XYZ", "POINT", "sfg")), structure(c(155933.561436732,
                                                                                                                                                                                                                                                                                                           517946.182550365, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(140802.697563979, 456881.771524581, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(154784.241643151, 545653.648132082,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(164026.007345779,
                                                                                                                                                                                                                                        496701.961412502, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(179364.066322246, 581994.125411096, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(188849.761738603, 524072.138117317,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(188318.790812958,
                                                                                                                                                                                                                                        452077.690368563, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(209047.270587744, 603272.335287218, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(214285.150917458, 494491.523943225,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(235129.986510439,
                                                                                                                                                                                                                                        529842.877962494, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(235179.970080805, 571581.223288614, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(242062.156554381, 454174.13350868,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(222025.617372105,
                                                                                                                                                                                                                                        621469.620167118, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(272803.150500692, 580257.816757263, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(257631.778530425, 477285.686814565,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(15204.9131692253,
                                                                                                                                                                                                                                        378794.067518989, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(30475.202390311, 385185.512969457, 0), class = c("XYZ",
                                                                                                                                                      "POINT", "sfg")), structure(c(33161.5063876291, 421402.391173403,
                                                                                                                                                                                    0), class = c("XYZ", "POINT", "sfg")), structure(c(6075.77556141675,
                                                                                                                                                                                                                                       392856.634215425, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(58430.2852418256, 385132.148328415, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(37843.1822665234, 408937.42539045,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(48393.4463326564,
                                                                                                                                                                                                                                        360739.898778152, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(59300.5268593911, 401696.034700946, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(68103.5303276381, 445602.269012438,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(72044.8590736535,
                                                                                                                                                                                                                                        388562.950364056, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(82345.1735737046, 384955.423944628, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(81058.2253902838, 434377.458939873,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(90380.9209645991,
                                                                                                                                                                                                                                        441925.910852381, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(123307.232881161, 442498.502534531, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(123715.725509022, 397548.014018176,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(138384.096674224,
                                                                                                                                                                                                                                        430076.049349805, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(154290.918489938, 384657.310483297, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(177127.990069963, 407846.337140399,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg")), structure(c(181267.254479522,
                                                                                                                                                                                                                                        356578.544033963, 0), class = c("XYZ", "POINT", "sfg")),
                                                                                         structure(c(181363.983663669, 324093.563434188, 0), class = c("XYZ",
                                                                                                                                                       "POINT", "sfg")), structure(c(211231.342699152, 390198.61162022,
                                                                                                                                                                                     0), class = c("XYZ", "POINT", "sfg"))), n_empty = 0L, crs = structure(list(
                                                                                                                                                                                       input = "EPSG:28992", wkt = "PROJCRS[\"Amersfoort / RD New\",\n    BASEGEOGCRS[\"Amersfoort\",\n        DATUM[\"Amersfoort\",\n            ELLIPSOID[\"Bessel 1841\",6377397.155,299.1528128,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4289]],\n    CONVERSION[\"RD New\",\n        METHOD[\"Oblique Stereographic\",\n            ID[\"EPSG\",9809]],\n        PARAMETER[\"Latitude of natural origin\",52.1561605555556,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",5.38763888888889,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9999079,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",155000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",463000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"easting (X)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"northing (Y)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Engineering survey, topographic mapping.\"],\n        AREA[\"Netherlands - onshore, including Waddenzee, Dutch Wadden Islands and 12-mile offshore coastal zone.\"],\n        BBOX[50.75,3.2,53.7,7.22]],\n    ID[\"EPSG\",28992]]"), class = "crs"), class = c("sfc_POINT",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "sfc"), precision = 0, bbox = structure(c(xmin = 6075.77556141675,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ymin = 324093.563434188, xmax = 272803.150500692, ymax = 621469.620167118
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ), class = "bbox"), z_range = structure(c(zmin = 0, zmax = 0), class = "z_range"))), row.names = c(NA,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     46L), sf_column = "geometry", agr = structure(c(StationID = NA_integer_,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Naam = NA_integer_), .Label = c("constant", "aggregate", "identity"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ), class = "factor"), class = c("sf", "tbl_df", "tbl", "data.frame"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ))


  #----
  #transform sf to equal projection as locations
  sf <- sf::st_transform(sf, crs = sf::st_crs(locations))

  #calc centroid of extend
  sf <- suppressWarnings(sf::st_union(sf::st_union(sf, sf, by_feature = TRUE)))
  sf <- suppressWarnings(sf::st_centroid(sf))

  #calc distance in km
  locations$`Distance (km)` <- as.numeric(sf::st_distance(locations$geometry, sf))/1000

  #remove geometry column
  locations$geometry <- NULL
  locations <- as.data.frame(locations)

  #sort table
  locations <- dplyr::arrange(locations, `Distance (km)`)

  #return
  return(locations)
}

